# Generated by Django 2.2 on 2020-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200623_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='stmp',
            field=models.TextField(default='http://127.0.0.1:8000/'),
        ),
    ]
